### ISSUE TITLE
Explicit path to `.so` file is needed on linux

### ISSUE THREAD

**Issue by k3yavi** [moor84/rust-to-python#1]
Hi, 
Thanks a lot for the awesome repo with the detailed example and the blogpost.
I am trying to compile the package subfolder of the repo, which compiles all right using the 
`python setup.py install` command however I get the following error when importing the python module.

```
╰─$ python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mylib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/avi/vpolo/rust-to-python/package/mylib/__init__.py", line 1, in <module>
    from .mylib import *
ModuleNotFoundError: No module named 'mylib.mylib'
```
 Once I change the sys.path to point it to the `so` library parent folder, python is able to work fine. I was wondering how can we automate the process ?

**Comment by moor84** [comment]
Hi, sorry for the late response.
I suspect you're trying to `import mylib` while being in the `package` folder? In this case, Python tries to import from local folder first, hence the confusion. Can you try running python from top-level directory?

**Comment by k3yavi** [comment]
duh ! You are right @moor84 , I can confirm it works once I run python from a directory other than the installed one.
Thanks a lot !
